RFC-0030/CFAR-929
cloudfoundry/rep pull request #56
Opened 2024-07-25 11:30 UTC by dimitardimitrov13

- [x] Read the [Contributing document](../blob/-/.github/CONTRIBUTING.md).

Summary
---------------
This PR is continuation for the [RFC-0030](https://github.com/cloudfoundry/community/blob/775c758343484edce85cd43c2627011bef9e8e16/toc/rfc/rfc-0030-add-support-for-file-based-service-binding.md)

Backward Compatibility
---------------
Breaking Change? **No**

This feature is the first PoC for RFC-0030.
Since the CAPI implementation for RFC-0030 is not done yet, the PR doesn't need to be applied immediately.

2024-12-13 16:24 UTC, ameowlia requested changes

2024-12-13 16:24 UTC, ameowlia commented on conversion_helpers_test.go
> +					It("allowing task to uses volumeMountedFiles", func() {
```suggestion
					It("uses volumeMountedFiles in the task", func() {
```

2024-12-13 16:24 UTC, ameowlia commented on conversion_helpers_test.go
> +					It("allowing task to uses volumeMountedFiles", func() {
❓ Is there a way to actually use volumeMountedFiles for a task? How does one enable that via the CC API?

2024-12-13 16:24 UTC, ameowlia commented on conversion_helpers_test.go
> +					VolumeMountedFiles:         []executor.VolumeMountedFiles{{Path: "/redis/username", Content: "redis_user"}},
❓ Can you add a test for when volumeMountedFiles are no provided, that the NewRunRequestFromDesiredLRP does not error?

2024-12-16 15:45 UTC, ameowlia commented on conversion_helpers_test.go
> +					It("allowing task to uses volumeMountedFiles", func() {
Thank @beyhan ! I didn't know you could run a task on an app 🤔 !

2024-12-20 09:46 UTC, dimitardimitrov13 commented
Hello @ameowlia, all comments were addressed.

2025-01-21 18:33 UTC, ameowlia approved these changes

2025-01-28 16:45 UTC, merged